---
title: "Prospective Students"
---

This is an exciting time for neuroimaging research at CSU. We have our own 3T scanner at the new CSU Translational Medicine Institute. Several faculty members who do neuroimaging have joined CSU in the past couple years as well across several departments (Psychology, Human Development and Family Studies, Occupational Therapy, Health and Exercise Science), and we are working together to develop new courses and new collaborations.

**What we are looking for in prospective graduate students:**

To be successful in graduate school a student must be intelligent, hard-working, and passionate about science. In admissions we use grades, recommendation letters, and other application materials primarily as clues as to whether a student has all these important qualities.

Students need not have undergraduate degrees in Psychology; Biology, Neuroscience, and related fields can provide an equally good foundation for cognitive psychology and cognitive neuroscience.

In addition because functional neuroimaging is a highly quantitative field; a background in mathematics, statistics and / or computer science is definitely a plus.

It is important to have research experience before committing to a Ph.D. program; the skills needed to excel in scientific research are not the same as those needed to do well in science courses. Many students who love to study science dislike the day to day challenges and frustrations of lab work.

## How to apply:

We admit students through the CSU Cognitive Psychology program ([link](https://graduateschool.colostate.edu/programs/psychology-phd/)) and through the Molecular, Cellular, and Integrative Neurosciences Program[(MCIN)](http://www.google.com/url?q=http%3A%2F%2Fmcin.colostate.edu%2F&sa=D&sntz=1&usg=AOvVaw25tnOhYc6BwgFNs_KzdkYh). **Students are strongly recommended to contact Carol Seger before applying so she will be aware of your application and can give you additional information about opportunities in the lab that may be a good match for your interests.**

## Prospective Undergraduate Students:

We also have openings for undergraduate research assistants. Most of our students are majoring in Neuroscience or in Psychology, but we have also had students from Biology and Computer Science. We especially are on the lookout for first or second year students who can be involved in the lab for a number of years. Students have the opportunity to get deeply involved in individual projects that can culminate in a senior thesis or other capstone project. Vulineering as a research assistant allows for flexible time commitments.

If you are interested, email Carol Seger (seger at colostate dot edu) for more information.
